/* Generated By:JJTree: Do not edit this line. AstDefExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

public
class AstDefExpression extends BaseNode {
    public AstDefExpression(int id) {
        super(id);
    }

    public AstDefExpression(ExpressionParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=4b4b29ad5e1d47565a4f176bf88bbb2b (do not edit this line) */
