/* Generated By:JJTree: Do not edit this line. AstExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

public
class AstExpression extends BaseNode {
    
    public AstExpression(int id) {
        super(id);
    }

    public AstExpression(ExpressionParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=ab2f609f18653a77b37b6827d8e368a8 (do not edit this line) */
