/* Generated By:JJTree: Do not edit this line. AstEvalExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

public
class AstEvalExpression extends BaseNode {
    public AstEvalExpression(int id) {
        super(id);
    }

    public AstEvalExpression(ExpressionParser p, int id) {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=f3262795e68e2758e91049e6e8e9eef3 (do not edit this line) */
