/* Generated By:JJTree: Do not edit this line. AstFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

import com.effacy.jui.platform.css.rebind.parser.AstRoot.Builder;

public
class AstFunction extends BaseNode {
    public AstFunction(int id) {
        super(id);
    }

    public AstFunction(ExpressionParser p, int id) {
        super(p, id);
    }

	@Override
	protected void build(Builder builder) {
		StringBuffer sb = new StringBuffer ();
        for (Node child : children) {
            if (!(child instanceof AstString))
                continue;
            if (!sb.isEmpty())
                sb.append ('.');
            sb.append (((AstString) child).image);
        }
        sb.append ("()");
        builder.expression = sb.toString ();
	}
    
}
/* JavaCC - OriginalChecksum=c5a48c0c9aba548cf2a8c456c12812db (do not edit this line) */
