/* Generated By:JJTree: Do not edit this line. AstRoot.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

public
class AstRoot extends BaseNode {
    private Builder builder;

    public AstRoot(int id) {
        super(id);
    }

    public AstRoot(ExpressionParser p, int id) {
        super(p, id);
    }

    public String reference() {
        if (builder == null) {
            builder = new Builder();
            super.build(builder);
        }
        return builder.reference;
    }

    public String expression() {
        if (builder == null) {
            builder = new Builder();
            super.build(builder);
        }
        return builder.expression;
    }

    public static class Builder {
        public String reference;
        public String expression;
    }
}
/* JavaCC - OriginalChecksum=059fc7516a265fed87b69b90a456de34 (do not edit this line) */
