/* Generated By:JJTree: Do not edit this line. AstString.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

import com.effacy.jui.platform.css.rebind.parser.AstRoot.Builder;

public
class AstString extends BaseNode {

    public AstString(int id) {
        super(id);
    }

    public AstString(ExpressionParser p, int id) {
        super(p, id);
    }

	@Override
	protected void build(Builder builder) {
		builder.expression = image;
	}
    
}
/* JavaCC - OriginalChecksum=d67e33a2f21eb7423d8a3a861006b4da (do not edit this line) */
