/* Generated By:JJTree: Do not edit this line. AstSubstitution.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.platform.css.rebind.parser;

import com.effacy.jui.platform.css.rebind.parser.AstRoot.Builder;

public
class AstSubstitution extends BaseNode {

    public AstSubstitution(int id) {
        super(id);
    }

    public AstSubstitution(ExpressionParser p, int id) {
        super(p, id);
    }

	@Override
	protected void build(Builder builder) {
        super.build (builder);
		builder.expression = "\"" + builder.expression + "\"";
	}

}
/* JavaCC - OriginalChecksum=528160b9f1e99f29c9b497fe86dffe84 (do not edit this line) */
