/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
package com.effacy.jui.platform.css.rebind.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 5;
  /** RegularExpression Id. */
  int COLOR_LITERAL = 6;
  /** RegularExpression Id. */
  int UNIT_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int DIGIT = 10;
  /** RegularExpression Id. */
  int ALPHA_CHAR = 11;
  /** RegularExpression Id. */
  int NUM_CHAR = 12;
  /** RegularExpression Id. */
  int ALPHANUM_CHAR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<IDENTIFIER>",
    "<COLOR_LITERAL>",
    "<UNIT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "\";\"",
    "\"@def\"",
    "\"@eval\"",
    "\".\"",
    "\"(\"",
    "\")\"",
  };

}
