/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 7.0.12 */
package com.effacy.jui.platform.css.rebind.parser;

public interface ExpressionParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTEXPRESSION = 1;
  public int JJTDEFEXPRESSION = 2;
  public int JJTEVALEXPRESSION = 3;
  public int JJTREFERENCE = 4;
  public int JJTFUNCTION = 5;
  public int JJTSUBSTITUTION = 6;
  public int JJTSTRING = 7;


  public String[] jjtNodeName = {
    "Root",
    "Expression",
    "DefExpression",
    "EvalExpression",
    "Reference",
    "Function",
    "Substitution",
    "String",
  };
}
/* JavaCC - OriginalChecksum=ff30f1d1d4926e2a78a6dbf0957afe72 (do not edit this line) */
