/*******************************************************************************
 * Copyright 2024 Jeremy Buckley
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * <a href= "http://www.apache.org/licenses/LICENSE-2.0">Apache License v2</a>
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package com.effacy.jui.core.client.util;

/**
 * Support class for creating page unique ID's.
 * 
 * @author Jeremy Buckley
 */
public final class UID {

    /**
     * The initial ID count.
     */
    private static int ID = 0;

    /**
     * Prefix for the IDs generated by this class.
     */
    private static final String PREFIX = "uid";


    /**
     * Private constructor.
     */
    private UID() {
        // Nothing.
    }


    /**
     * Creates a locally (page) unique ID.
     * 
     * @return The unique ID.
     */
    public static String createUID() {
        return PREFIX + (ID++);
    }
}
