/*******************************************************************************
 * Copyright 2024 Jeremy Buckley
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * <a href= "http://www.apache.org/licenses/LICENSE-2.0">Apache License v2</a>
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package com.effacy.jui.rpc.extdirect;

/**
 * Error handler for processing remote methods exceptions. Error handlers are
 * invoked if a remote method generates an exception (this includes an exception
 * being generated by transaction support when transactions are enabled). It
 * allows a remote method to define an error handling behaviour that is
 * different from the default ExtJS stack error handling (which returns an
 * exception response to the client).
 * 
 * @author Jeremy Buckley
 */
public interface IActionErrorHandler {

    /**
     * Determines if this type of error is something we should retry.
     * 
     * @param e
     *            the exception.
     * @return {@code true} if the error should be retried.
     */
    public boolean retryError(Throwable e);


    /**
     * Handle the given error returning a suitable response.
     * 
     * @param call
     *            the call that generated the error.
     * @param e
     *            the error to handle.
     * @return The response to return.
     */
    public Object handleError(RemoteCallRequest call, Throwable e);
}
