/*******************************************************************************
 * Copyright 2024 Jeremy Buckley
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * <p>
 * <a href= "http://www.apache.org/licenses/LICENSE-2.0">Apache License v2</a>
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package com.effacy.jui.playground.ui.tutorial;

/**
 * Collection of random names.
 */
public class Names {

    public final static String[] NAMES = { "Louise Brady", "Reed Todd", "Zariah Meadows", "Wayne Torres", "Violet Glover", "Mack Ahmed", "Jolie Goodwin", "Kaison Reynolds", "Isabelle Finley", "Calum Copeland", "Dayana Cunningham", "Alejandro Mills", "June Tucker", "Ivan Harris", "Penelope Reed", "Easton Mack", "Nadia Ho", "Morgan Ochoa", "Luciana Frazier", "Callum Carr", "Rowan Rocha",
            "Onyx Camacho", "Armani Perry", "Waylon Skinner", "Mara Berg", "Cayson Potter", "Rory Hawkins", "Victor Hansen", "Hope Mata", "Ray Miller", "Isabella Hodges", "Alonzo Woods", "Reese Lloyd", "Zaire Reyes", "Audrey Mitchell", "Jaxon Palacios", "Bria Cobb", "Raphael Glass", "Clare Estrada", "Phoenix Landry", "Brynleigh Guevara", "Tommy Combs", "Irene Small", "Rudy Zavala", "Liv Diaz",
            "Nathan Dominguez", "Raegan Villalobos", "Reuben Bender", "Lilyana Graham", "Giovanni Jacobson", "Royal McCoy", "Jett Newton", "Braelynn Buchanan", "Enrique McConnell", "Denise Atkins", "Cason Dominguez", "Raegan Blake", "Zyaire Dean", "Julianna Hunt", "Jesus Ochoa", "Luciana Guerrero", "Bryce Quinn", "Heaven Robertson", "Emiliano Gordon", "Taylor Wu", "Kyson Maxwell", "Kyla Vu",
            "Kamdyn Baker", "Isla Doyle", "Kashton Hamilton", "Mackenzie Leonard", "Ricardo Meyers", "Leyla Barrett", "Angelo Hopkins", "Gabriela Salazar", "Brody Gallegos", "Ari Gomez", "Isaiah Carr", "Rowan Schaefer", "Ishaan O’Connell", "Jillian Herrera", "River Blevins", "Aila Conley", "Marvin Gallagher", "Elliott Castillo", "Kai Spears", "Isabela Charles", "Conrad Case", "Cleo Knapp",
            "Boden Phan", "Elsa Lynn", "Zechariah Sanford", "Emerald Fernandez", "Bentley Gross", "Angel Hayes", "Legend Jarvis", "Elisabeth Robinson", "Matthew Camacho", "Armani Townsend", "Alexis Underwood", "Ensley Vu", "Kamdyn Orozco", "Renata Alfaro", "Xzavier Solis", "Miracle Ingram", "Tripp Adams", "Stella Douglas", "Derek Ho", "Calliope Stanton", "Zyair Foster", "Brielle Dickerson",
            "Flynn Cohen", "Destiny Richardson", "Robert Melton", "Kamiyah Salazar", "Brody Walter", "Penny Dominguez", "Kaden McMillan", "Oakleigh Schmidt", "Zayden Booth", "Zariyah Lin", "Conor Villarreal", "Jazlyn Sharp", "Royce Gillespie", "Alianna Krueger", "Jones Tucker", "Esther Fox", "Antonio Barber", "Cassidy McLaughlin", "Ibrahim Benton", "Anais Browning", "Rohan Carrillo",
            "Kaylani Gilbert", "Tobias Lane", "Amy Cortez", "Zayn Brown", "Charlotte Vang", "Jimmy Dorsey", "Addyson Hughes", "Everett Levy", "Flora Castaneda", "Collin Fields", "Annie Davidson", "Dante Clements", "Cara Poole", "Quincy Cortes", "Lea Walton", "Dominick Portillo", "Nathalie Tate", "Dalton Bradford", "Rhea Suarez", "Soren Dixon", "Blakely Hendricks", "Dash Craig", "Brynn Ferguson",
            "Miguel Patrick", "Lyra Proctor", "Vance Curtis", "Alexis Drake", "Jalen Dyer", "Estrella Washington", "Juan Gates", "Melina Huff", "Finnley Cline", "Lina Giles", "Kole Bond", "Alena Harrington", "Omari Roach", "Lyanna Watts", "Dakota Gardner", "Jordyn Higgins", "Sterling Barnes", "Liliana Gutierrez", "Luca Ellis", "Ayla Herman", "Juelz Strickland", "Nia Barry", "Emery Bridges",
            "Elora Choi", "Khari Jaramillo", "Guadalupe Wells", "Max Brewer", "Thea Gibson", "Tyler Warren", "Sloane Barnett", "Stephen Juarez", "Juliet McKay", "Joey Prince", "Greta Walton", "Dominick Webb", "Ariella Gibbs", "Deacon Booth", "Zariyah English", "Junior Fisher", "Arya Thornton", "Malik English", "Kelly French", "Corey Conner", "Alondra Schroeder", "Izaiah Horne", "Marlowe Sosa",
            "Emir Decker", "Aleena Howell", "Bradley Bonilla", "Romina Hale", "Ezequiel Romero", "Eliza Lester", "Lee Williams", "Ava Barry", "Emery Ford", "Alexandra Grant", "Leon Frazier", "Octavia Camacho", "Tatum Camacho", "Armani Nguyen", "Gabriel Fernandez", "Amara Moore", "Levi Hendrix", "Zhuri McMillan", "Rocky Knox", "Kallie Wright", "Grayson Matthews", "Lila Hull", "Salem Pena",
            "Rachel Munoz", "Justin Patterson", "Kaylee Livingston", "Ambrose Holland", "Mariah Garcia", "James Morgan", "Delilah Bond", "Roger McGee", "Kayleigh Prince", "Aron Rios", "Brooke Armstrong", "Grant Pineda", "Nola Wiley", "Mathew Barrett", "Kendall Higgins", "Sterling Roberts", "Paisley Walker", "Luke Kelly", "Ruby Reynolds", "Vincent Henry", "Summer Greene", "Griffin Lester",
            "Averi Rowe", "Kamden Buckley", "Theodora Garza", "Judah Greene", "Selena Herring", "Henrik Fox", "Juliette Burton", "Zander Delacruz", "Celine Olsen", "Skyler Ahmed", "Jolie Daniel", "Grady Woodard", "Aubrie Davis", "Lucas Rogers", "Madelyn Jones", "William Schaefer", "Mavis Farley", "Graysen Vaughn", "Reign Collins", "Miles Walter", "Penny Maxwell", "Eden Stevens", "Katherine Ward",
            "Jameson Macdonald", "Rosalia Fischer", "Leonidas Proctor", "Chandler Maddox", "Lyric Collins", "Kinsley Franco", "Gage Hail", "Lainey Estes", "Hakeem Ramsey", "Lyric Hart", "Joel Delgado", "Alani Lam", "Bodie Rush", "Maleah Barton", "Cassius Marks", "Monica Stewart", "Nolan Parks", "Ainsley Lucas", "Chance Simmons", "Reagan Dudley", "Colter Crawford", "Aubree Orozco", "Keanu Munoz",
            "Kehlani Simpson", "Elliott Pennington", "Yareli Collier", "Edison Klein", "Elianna Reyna", "Reginald Zamora", "Sierra Aguilar", "Milo McIntosh", "Gwen Estrada", "Phoenix Atkins", "Mina Atkinson", "Duke Rogers", "Madelyn Rojas", "Colin McFarland", "Annika Anderson", "Jacob Reynolds", "Isabelle Jones", "William Lyons", "Kenzie Ramirez", "David Reynolds", "Isabelle Miranda",
            "Rory Little", "Harley Miller", "Benjamin Miller", "Isabella Trevino", "Jaime Murillo", "Mikaela Rangel", "Saint Meza", "Rosa Weber", "Crew Gardner", "Jordyn O’Neill", "Marcel Harrison", "Jasmine Ross", "Wesley Grant", "Alaina Conrad", "Dilan Vega", "Dakota Browning", "Rohan Wilkins", "Amalia Griffith", "Franklin Johnson", "Emma Hendricks", "Dash McIntosh", "Gwen Lucero",
            "Felipe Bridges", "Elora Stark", "Kristopher Rubio", "Hadassah Stephens", "Messiah Webster", "Kensley Murphy", "Cameron Cabrera", "Daleyza Compton", "Abner Montes", "Roselyn Sheppard", "Trent McDowell", "Rayna Saunders", "Kasen Curtis", "Alexis Maxwell", "Eden Figueroa", "Lilith Terrell", "Jaxen White", "Layla Burgess", "Kolton Floyd", "Yaretzi Calderon", "Oakley Roberts",
            "Paisley White", "Aiden Winters", "Kataleya Lewis", "Wyatt Waters", "Bristol Oliver", "Karson Felix", "Paisleigh Rivers", "Bear Duncan", "Elise Correa", "Zakai Tucker", "Esther Lopez", "Michael Gordon", "Taylor Hoffman", "Steven Hayden", "Avayah Russo", "Jamie Simon", "Kalani Gregory", "Travis Burgess", "Emory Meza", "Lucian Cross", "Nayeli Kramer", "Kylan Moyer", "Zola Mullen",
            "Shepard Taylor", "Sofia Clements", "Fisher McKee", "Kori Lloyd", "Zaire McKenzie", "Briar Wagner", "Enzo Baxter", "Lara Yu", "Bryant Aguilar", "Josie Blake", "Zyaire Weeks", "Karen Flores", "Lincoln Cruz", "Claire Booth", "Chaim Fields", "Annie Eaton", "Leighton Luna", "Journey Alexander", "Kingston Clarke", "Kaitlyn Andrews", "Lukas Huff", "Karsyn Morris", "Christian Patton",
            "Lorelei Vasquez", "Rowan Wells", "Cecilia Aguirre", "Andy Pratt", "Ailani Shelton", "Leonel Pitts", "Nala Villa", "Clay Macias", "Adley Hale", "Ezequiel Herring", "Denver Andrade", "Abdiel Snyder", "Callie Rhodes", "Titus Cisneros", "Janelle Cisneros", "Alden Glover", "Alessia Jimenez", "Silas Le", "Myla Paul", "Noel Lawrence", "Lauren Banks", "Martin Farmer", "Madelynn Watson",
            "Greyson Khan", "Mabel Clarke", "Stetson Faulkner", "Ansley Hull", "Salem Li", "Paige Mayo", "Jericho Lynch", "Malia O’Connell", "Jovanni Gibbs", "Carter Morrison", "Maximus Jones", "Sophia Dodson", "Seven Mitchell", "Willow Pruitt", "Gatlin Suarez", "Jimena Alvarez", "Xavier Rangel", "Gloria Bentley", "Randy Cabrera", "Daleyza Padilla", "Jaden Montes", "Roselyn Edwards",
            "Adrian Sellers", "Mercy Cannon", "Archie Wilkinson", "Siena McKinney", "Romeo Porter", "Ryleigh Mullen", "Shepard Lyons", "Kenzie Bishop", "Paxton Portillo", "Nathalie Donaldson", "Canaan Ponce", "Aileen Schultz", "Cody Hayes", "Iris Pennington", "Bobby Wood", "Natalia Bass", "Landen Levy", "Flora Meza", "Lucian Moss", "Bianca Davidson", "Dante Kemp", "Anika Zuniga",
            "Sincere Osborne", "Shelby Gordon", "Karter Gross", "Angel Rhodes", "Titus Colon", "Remy Tanner", "Bruno Fitzgerald", "Marlee Cameron", "Rayan McConnell", "Denise Santiago", "Beckham Bishop", "Brooklynn Cervantes", "Kamari Houston", "Lylah Barron", "Dustin Logan", "Kora Dalton", "Fletcher Lawson", "Phoebe Velazquez", "Drew Jacobson", "Royal Mendoza", "Dominic Jaramillo",
            "Guadalupe Hail", "Hector Costa", "Robin Chan", "Frank Maxwell", "Kyla Harrison", "Gavin Clayton", "Saige Lindsey", "Jayson Gonzalez", "Abigail Madden", "Everest Reid", "Charlee Vaughan", "Castiel Melton", "Kamiyah Andersen", "Alistair Armstrong", "Presley Farrell", "Ty Olson", "Isabel Larson", "Rafael Pennington", "Yareli Galindo", "Salvatore Cherry", "Nyomi Stone", "Finn Velazquez",
            "Jaliyah Harvey", "Cayden Shepherd", "Katalina Suarez", "Soren Lim", "Giavanna Marsh", "Bo Dalton", "Lilian Sexton", "Mylo Gallegos", "Ari Bentley", "Randy Velez", "Megan Davis", "Lucas Malone", "Skyler Lowe", "Julius Castillo", "Eva Rosales", "Wilder Hill", "Hannah Li", "Jorge Montgomery", "Evangeline Kline", "Ramon Solomon", "Mylah Cain", "Benson Oliver", "Camille Heath",
            "Lionel Kramer", "Hanna Pham", "Russell Caldwell", "Evelynn Weeks", "Anders Eaton", "Miley Sharp", "Royce Richardson", "Allison Evans", "Elias Dejesus", "Julissa Colon", "Bruce Montgomery", "Evangeline Fitzgerald", "Peyton Castillo", "Eva Boone", "Mauricio Herman", "Paulina McIntyre", "Eliseo Wilkerson", "Janiyah Benjamin", "Kyro Ramos", "Alice Schmitt", "Murphy Sloan",
            "Selene Becker", "Lawson Dougherty", "Alisson Gonzales", "Brayden Hart", "Gemma Murphy", "Cameron Burke", "Vera Carey", "Watson Chen", "Valeria Villarreal", "Nikolai O’Neill", "Kenna Casey", "Armando Horne", "Marlowe Delarosa", "Osiris May", "Adriana Reid", "Josue Richards", "Trinity Rosas", "Remi Cervantes", "Aylin Cherry", "Rome Stanley", "Gracelyn Tang", "Rogelio Corona",
            "Marianna Wolfe", "Donovan Santana", "Myra Love", "Jeffrey Stokes", "Miranda Wells", "Max Meyer", "Sara Dillon", "Alvin Bradford", "Rhea Matthews", "Preston Barajas", "Keilani Morse", "Bode Calderon", "Serena Sampson", "Cain Gentry", "Amelie Sullivan", "Evan Gregory", "Alaya Camacho", "Tatum Blankenship", "Rosalee Stafford", "Alfredo Ray", "Ruth Dawson", "Iker Conner",
            "Alondra Bullock", "Ben Holt", "Adelynn Warner", "Jaxton Mills", "June Lane", "Matias Brewer", "Thea Santana", "Mohamed Wallace", "Arianna Powell", "Bennett Montgomery", "Evangeline McMahon", "Jakob Hull", "Andi Alfaro", "Xzavier Goodman", "Carolina Smith", "Liam Bass", "Zahra Arias", "Alec Montoya", "Kamryn McClain", "Mitchell Randall", "Christina Sharp", "Royce Valencia",
            "Maddison Lee", "Jack Herrera", "Ximena Winters", "Deandre Ibarra", "Madilynn Velez", "Kareem Roach", "Lyanna Gonzalez", "Ethan Austin", "Alivia Herman", "Juelz Rangel", "Gloria Rodgers", "Mathias Stanley", "Gracelyn Wheeler", "Kenneth Schultz", "Briella Aguilar", "Milo Peters", "Leila Berger", "Byron Willis", "Alexa Huber", "Mac Livingston", "Milena Garrison", "Noe McLaughlin",
            "Stephanie Jennings", "Corbin Burgess", "Emory Bailey", "Axel Stanley", "Gracelyn Leonard", "Ricardo O’Donnell", "Bellamy Shields", "Devon Boyd", "Georgia Compton", "Abner Huff", "Karsyn Peck", "Yousef Li", "Paige Barber", "Solomon Copeland", "Dayana Frazier", "Callum White", "Layla Duke", "Kalel Good", "Nathalia Fischer", "Leonidas Hart", "Gemma Soto", "Barrett Vang", "Madisyn David",
            "Alonso Moore", "Emily Deleon", "Nasir Macdonald", "Rosalia Blankenship", "Ernesto Brady", "Ryan Tucker", "Ivan Lara", "Heidi Hawkins", "Victor McKenzie", "Briar Knight", "Beckett Marquez", "Milani Beck", "Eduardo Frost", "Paula Spencer", "Ace Hart", "Gemma Guerra", "Leland Pennington", "Yareli Walls", "Larry Norman", "Malani Mullins", "Allen McIntosh", "Gwen Golden", "Amias McGuire",
            "April Waters", "Maximilian Flowers", "Ariya Robles", "Otto McMahon", "Belen Johnston", "Felix Christian", "Anahi Cameron", "Rayan Bowman", "Fiona Clayton", "Boston Holland", "Mariah Richmond", "Mordechai Shepherd", "Katalina Rivers", "Bear Hanna", "Cynthia Cruz", "Ryan Vance", "Maxine Duarte", "Abdullah Reilly", "Tori Snyder", "Thiago Fitzgerald", "Marlee McPherson", "Foster Jones",
            "Sophia McDaniel", "Major Carpenter", "Lilly Li", "Jorge Leblanc", "Novalee Adkins", "Kylo Olsen", "Oaklyn Whitehead", "Zayd Drake", "Jayleen Rush", "Kaiser Jimenez", "Adeline Morton", "Roland Shaffer", "Alanna Tapia", "Samir King", "Victoria Randall", "Trenton Shah", "Angelica Schroeder", "Izaiah Hinton", "Jaelynn Herring", "Henrik Vargas", "Andrea Elliott", "Blake Sutton",
            "Izabella Choi", "Khari Simon", "Kalani Vaughan", "Castiel Orr", "Alaiya Lozano", "Boone Rosas", "Joelle Pope", "Gunnar Ahmed", "Jolie Pollard", "Jad Suarez", "Jimena Reynolds", "Vincent Villarreal", "Jazlyn Mayo", "Jericho Estrada", "Sawyer Kirby", "Tony Cain", "Kendra Morgan", "Hunter Sanders", "Everleigh Beard", "Nathanael Morrow", "Reyna King", "Julian Ahmed", "Jolie Huffman",
            "Chris Mosley", "Zaniyah Hardin", "Hassan Craig", "Brynn Lopez", "Michael Velazquez", "Jaliyah Carpenter", "Jeremy Abbott", "Melany Yates", "Braylon Glover", "Alessia Gentry", "Magnus Archer", "Kadence Guevara", "Tommy Livingston", "Milena Tran", "Braxton Jordan", "Adalynn Hardy", "Jayceon Valentine", "August Corona", "Darian Christian", "Anahi Park", "Daxton Fowler", "Lennon Duarte",
            "Abdullah Acevedo", "Ashlynn Norton", "Callen Roth", "Elliot Hanson", "Khalil Hancock", "Katelyn Molina", "Prince Dominguez", "Raegan Wall", "Issac Robles", "Felicity Rojas", "Colin Faulkner", "Ansley Wilson", "Daniel Bowers", "Elisa McClain", "Mitchell Cobb", "Aviana Becker", "Lawson Mullen", "Shay Larsen", "Brycen Collier", "Ivory Schneider", "Raymond Rodgers", "Selah Hahn",
            "Kabir Elliott", "Noelle Rosario", "Jedidiah Sandoval", "Elsie Walter", "Lochlan Grant", "Alaina Sparks", "Drake Rich", "Sunny Ramsey", "Luciano Paul", "Daphne Weaver", "Tucker Parsons", "Maia Sampson", "Cain Novak", "Kaiya Stephenson", "Joe Walker", "Hazel Robbins", "Finnegan Trujillo", "Danielle Gonzales", "Brayden Norris", "Arielle York", "Leandro Romero", "Eliza Esquivel",
            "Bridger Combs", "Irene Duncan", "Avery Hendricks", "Dani Hamilton", "Jason Shepherd", "Katalina Salinas", "Edgar Esquivel", "Jaylee Murray", "Ashton Cantu", "Galilea Brown", "Elijah Morton", "Mallory Medina", "George Lozano", "Cecelia Gross", "Quinn Small", "Zaria Clayton", "Boston Pierce", "Arabella Brady", "Reed Hudson", "Kamila Cole", "Nathaniel Hickman", "Scarlette Ramsey",
            "Luciano Esquivel", "Jaylee Person", "Moses Vazquez", "Journee Delacruz", "Memphis Hahn", "Fallon Miller", "Benjamin Novak", "Kaiya Garcia", "James Maxwell", "Kyla Bowen", "Trevor Kirby", "Skyla Alfaro", "Xzavier Jefferson", "Julieta Beasley", "Stanley Whitaker", "Ivanna Farrell", "Ty Lynch", "Malia Perez", "Owen Stevens", "Katherine Osborne", "Augustus Rogers", "Madelyn Palmer",
            "Theo Cooper", "Serenity Hawkins", "Victor Sparks", "Aisha Sawyer", "Jefferson Caldwell", "Evelynn Gardner", "Alan Clay", "Aliana Li", "Jorge Rowe", "Matilda Flores", "Lincoln Hood", "Briana Stafford", "Alfredo Lynn", "Samira McLean", "Crosby Freeman", "Norah Bartlett", "Kace Browning", "Princess Compton", "Abner Simmons", "Reagan Allison", "Dennis Moody", "Elaine Tang",
            "Rogelio Chang", "Ophelia Payne", "Edward Walton", "Scarlet Steele", "Elian Bryan", "Meredith Underwood", "Reece Armstrong", "Presley Brewer", "Cruz Mora", "Jemma Aguilar", "Milo Wilkins", "Amalia Kim", "Roman Schwartz", "Lilliana Madden", "Everest Wagner", "Maeve Hunt", "Jesus Pitts", "Nala Fuller", "Andre McMahon", "Belen Compton", "Abner Morris", "Genesis O’Neal", "Eddie Schmitt",
            "Queen Goodwin", "Kaison Foster", "Brielle Cohen", "Killian Rivera", "Lillian Holt", "Niko Garner", "Jacqueline Harper", "Hayes Johnston", "Laila Mosley", "Rayden Stephens", "Millie Heath", "Lionel Herrera", "Ximena Alfaro", "Xzavier Decker", "Aleena Pugh", "Judson Espinosa", "Braylee Le", "Damien Castillo", "Eva Wilkinson", "Leonard Archer", "Kadence Novak", "Bishop Walton",
            "Scarlet Villarreal", "Nikolai Duncan", "Elise Daniels", "Xander Sanders", "Everleigh Webster", "Shawn Wiley", "Lauryn Bernard", "Jair Burke", "Vera Taylor", "Jackson King", "Victoria Herrera", "River Gardner", "Jordyn Correa", "Zakai Lee", "Scarlett Peterson", "Santiago Wilkins", "Amalia Byrd", "Cristian Barnes", "Liliana Stark", "Kristopher Hickman", "Scarlette Graves", "Cesar Pugh",
            "Landry Reynolds", "Vincent Guerra", "Edith Nichols", "Atlas Stokes", "Miranda Ali", "Arjun Jordan", "Adalynn Odom", "Kylian Leach", "Martha Jenkins", "Declan Mays", "Denisse McLaughlin", "Ibrahim Howard", "Sophie O’Connor", "Princeton Avila", "Amiyah Schroeder", "Izaiah Miles", "Alessandra Dougherty", "Brett Salgado", "Avalynn Moore", "Levi Gilbert", "Jocelyn Webb",
            "Lorenzo Jaramillo", "Guadalupe May", "Finley Kerr", "Baylee Cortez", "Zayn Sparks", "Aisha Dyer", "Atreus Brooks", "Autumn Finley", "Calum Magana", "Amaris Guerrero", "Bryce Atkinson", "Jazmin Ramos", "Angel Nielsen", "Vienna Duarte", "Abdullah Ruiz", "Emery Sampson", "Cain Buck", "Livia Farrell", "Ty Bell", "Melody Horne", "Zev Howard", "Sophie Brady", "Reed Leon" };
}