/* Generated By:JJTree: Do not edit this line. AstAndExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstAndExpression extends BaseNode {
  public AstAndExpression(int id) {
    super(id);
  }

  public AstAndExpression(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1557aa195d2fcbf8e80aeeea37223679 (do not edit this line) */
