/* Generated By:JJTree: Do not edit this line. AstContains.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstContains extends BaseNode {
  public AstContains(int id) {
    super(id);
  }

  public AstContains(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a34550cd612197774fb239baf606666f (do not edit this line) */
