/* Generated By:JJTree: Do not edit this line. AstEndsWith.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstEndsWith extends BaseNode {
  public AstEndsWith(int id) {
    super(id);
  }

  public AstEndsWith(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8574d1f641e37f556ca92f1a2d359e36 (do not edit this line) */
