/* Generated By:JJTree: Do not edit this line. AstEquals.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstEquals extends BaseNode {
  public AstEquals(int id) {
    super(id);
  }

  public AstEquals(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73d4e4d86550aa5e470b40b5baf1d33f (do not edit this line) */
