/* Generated By:JJTree: Do not edit this line. AstField.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstField extends BaseNode {
  public AstField(int id) {
    super(id);
  }

  public AstField(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aa2430075ef514efa0dc4b4ea4c3ec7b (do not edit this line) */
