/* Generated By:JJTree: Do not edit this line. AstFalseExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstFalseExpression extends BaseNode {
  public AstFalseExpression(int id) {
    super(id);
  }

  public AstFalseExpression(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1a2657c76081b99bcbd690aa4b92ce6 (do not edit this line) */
