/* Generated By:JJTree: Do not edit this line. AstGreaterThanOrEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstGreaterThanOrEqual extends BaseNode {
  public AstGreaterThanOrEqual(int id) {
    super(id);
  }

  public AstGreaterThanOrEqual(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c9b183dbd0b9a617fb926c5e1c35327e (do not edit this line) */
