/* Generated By:JJTree: Do not edit this line. AstGreaterThan.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstGreaterThan extends BaseNode {
  public AstGreaterThan(int id) {
    super(id);
  }

  public AstGreaterThan(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=568ea3ab4d6137f0ee518309940b206f (do not edit this line) */
