/* Generated By:JJTree: Do not edit this line. AstIn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstIn extends BaseNode {
  public AstIn(int id) {
    super(id);
  }

  public AstIn(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86b22cd38f3f7fff69f21ff4c4e83715 (do not edit this line) */
