/* Generated By:JJTree: Do not edit this line. AstIs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstIs extends BaseNode {
  public AstIs(int id) {
    super(id);
  }

  public AstIs(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab97f9e30288dfee7b47131c2e941da6 (do not edit this line) */
