/* Generated By:JJTree: Do not edit this line. AstList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstList extends BaseNode {
  public AstList(int id) {
    super(id);
  }

  public AstList(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5aea774711ee2f6df39a9569ee13b24a (do not edit this line) */
