/* Generated By:JJTree: Do not edit this line. AstLessThan.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstLessThan extends BaseNode {
  public AstLessThan(int id) {
    super(id);
  }

  public AstLessThan(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b10535b63e8f32b74109dad2a6aa5eba (do not edit this line) */
