/* Generated By:JJTree: Do not edit this line. AstLessThanOrEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstLessThanOrEqual extends BaseNode {
  public AstLessThanOrEqual(int id) {
    super(id);
  }

  public AstLessThanOrEqual(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d929121a31a10422e03ff1254662dbd5 (do not edit this line) */
