/* Generated By:JJTree: Do not edit this line. AstNotExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstNotExpression extends BaseNode {
  public AstNotExpression(int id) {
    super(id);
  }

  public AstNotExpression(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a6a8a394494387fdf682ac423558a262 (do not edit this line) */
