/* Generated By:JJTree: Do not edit this line. AstNotEquals.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstNotEquals extends BaseNode {
  public AstNotEquals(int id) {
    super(id);
  }

  public AstNotEquals(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a453bd13aa76b81507225c6089e41b00 (do not edit this line) */
