/* Generated By:JJTree: Do not edit this line. AstNotIn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstNotIn extends BaseNode {
  public AstNotIn(int id) {
    super(id);
  }

  public AstNotIn(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8df98a5e791be0760e7651a1a66b8a5a (do not edit this line) */
