/* Generated By:JJTree: Do not edit this line. AstOrExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstOrExpression extends BaseNode {
  public AstOrExpression(int id) {
    super(id);
  }

  public AstOrExpression(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ab7aa62781b0d32812fab8e00bc80b9 (do not edit this line) */
