/* Generated By:JJTree: Do not edit this line. AstRoot.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstRoot extends BaseNode {
  public AstRoot(int id) {
    super(id);
  }

  public AstRoot(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f27670adff42342efb275ec6ee2bf7f9 (do not edit this line) */
