/* Generated By:JJTree: Do not edit this line. AstStartsWith.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstStartsWith extends BaseNode {
  public AstStartsWith(int id) {
    super(id);
  }

  public AstStartsWith(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=057a4b18c7bf4d259e83a779674cd456 (do not edit this line) */
