/* Generated By:JJTree: Do not edit this line. AstTrueExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstTrueExpression extends BaseNode {
  public AstTrueExpression(int id) {
    super(id);
  }

  public AstTrueExpression(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1013ca29920104e0258a8f2e0c9053c (do not edit this line) */
