/* Generated By:JJTree: Do not edit this line. AstValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.effacy.jui.filter.parser;

public
class AstValue extends BaseNode {
  public AstValue(int id) {
    super(id);
  }

  public AstValue(FilterQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b627bd5af074404b2e909ebd1f30bea1 (do not edit this line) */
