/* Generated By:JavaCC: Do not edit this line. FilterQueryParserTreeConstants.java Version 7.0.13 */
package com.effacy.jui.filter.parser;

public interface FilterQueryParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTOREXPRESSION = 2;
  public int JJTANDEXPRESSION = 3;
  public int JJTNOTEXPRESSION = 4;
  public int JJTTRUEEXPRESSION = 5;
  public int JJTFALSEEXPRESSION = 6;
  public int JJTEQUALS = 7;
  public int JJTNOTEQUALS = 8;
  public int JJTGREATERTHAN = 9;
  public int JJTGREATERTHANOREQUAL = 10;
  public int JJTLESSTHAN = 11;
  public int JJTLESSTHANOREQUAL = 12;
  public int JJTIN = 13;
  public int JJTNOTIN = 14;
  public int JJTCONTAINS = 15;
  public int JJTSTARTSWITH = 16;
  public int JJTENDSWITH = 17;
  public int JJTFIELD = 18;
  public int JJTVALUE = 19;
  public int JJTLIST = 20;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "TrueExpression",
    "FalseExpression",
    "Equals",
    "NotEquals",
    "GreaterThan",
    "GreaterThanOrEqual",
    "LessThan",
    "LessThanOrEqual",
    "In",
    "NotIn",
    "Contains",
    "StartsWith",
    "EndsWith",
    "Field",
    "Value",
    "List",
  };
}
/* JavaCC - OriginalChecksum=b50aa2cef35dfddc4ada76352172af5b (do not edit this line) */
