/* Generated By:JavaCC: Do not edit this line. FilterQueryParserTreeConstants.java Version 7.0.13 */
package com.effacy.jui.filter.parser;

public interface FilterQueryParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTOREXPRESSION = 2;
  public int JJTANDEXPRESSION = 3;
  public int JJTNOTEXPRESSION = 4;
  public int JJTEQUALS = 5;
  public int JJTNOTEQUALS = 6;
  public int JJTGREATERTHAN = 7;
  public int JJTGREATERTHANOREQUAL = 8;
  public int JJTLESSTHAN = 9;
  public int JJTLESSTHANOREQUAL = 10;
  public int JJTIN = 11;
  public int JJTNOTIN = 12;
  public int JJTCONTAINS = 13;
  public int JJTSTARTSWITH = 14;
  public int JJTENDSWITH = 15;
  public int JJTFIELD = 16;
  public int JJTVALUE = 17;
  public int JJTLIST = 18;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "Equals",
    "NotEquals",
    "GreaterThan",
    "GreaterThanOrEqual",
    "LessThan",
    "LessThanOrEqual",
    "In",
    "NotIn",
    "Contains",
    "StartsWith",
    "EndsWith",
    "Field",
    "Value",
    "List",
  };
}
/* JavaCC - OriginalChecksum=ad5138c80d35755499cdce0a72753125 (do not edit this line) */
