/* Generated By:JJTree&JavaCC: Do not edit this line. FilterQueryParserConstants.java */
package com.effacy.jui.filter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FilterQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int EQ = 8;
  /** RegularExpression Id. */
  int NEQ = 9;
  /** RegularExpression Id. */
  int GT = 10;
  /** RegularExpression Id. */
  int GTE = 11;
  /** RegularExpression Id. */
  int LT = 12;
  /** RegularExpression Id. */
  int LTE = 13;
  /** RegularExpression Id. */
  int IN = 14;
  /** RegularExpression Id. */
  int NOT_IN = 15;
  /** RegularExpression Id. */
  int CONTAINS = 16;
  /** RegularExpression Id. */
  int STARTS_WITH = 17;
  /** RegularExpression Id. */
  int ENDS_WITH = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int LBRACKET = 21;
  /** RegularExpression Id. */
  int RBRACKET = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int NULL = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int DECIMAL = 29;
  /** RegularExpression Id. */
  int IDENTIFIER = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<EQ>",
    "<NEQ>",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "<IN>",
    "<NOT_IN>",
    "<CONTAINS>",
    "<STARTS_WITH>",
    "<ENDS_WITH>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<STRING>",
    "\"true\"",
    "\"false\"",
    "<NULL>",
    "<INTEGER>",
    "<DECIMAL>",
    "<IDENTIFIER>",
  };

}
