#
# Activated on PR into main (from develop). Performs a set of pre-release checks followed
# by a build and test.
#
name: PR checks (main)

on:
  pull_request:
    branches:
      - main

jobs:

  run_checks:
    if: github.head_ref == 'develop'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Verify pre-release requisites
        run: mvn enforcer:enforce -Pprerelease-checks

      - name: Build project
        run: mvn -B package --file pom.xml

