name: Publish package to the Maven Central Repository
on:
  release:
    types: 
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Validate release tag format
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          if [[ ! "$TAG_NAME" =~ ^version/[0-9]+\.[0-9]+\.[0-9]+([.-][A-Za-z0-9]+)*$ ]]; then
            echo "Error: Tag name '$TAG_NAME' does not match the required format 'version/X.Y.Z[.*]'"
            exit 1
          fi
          echo "Tag name '$TAG_NAME' is valid."

      - name: Extract revision from tag
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          REVISION="${TAG_NAME#version/}"
          echo "REVISION=$REVISION" >> $GITHUB_ENV
          echo "Extracted revision: $REVISION"

      - name: Publish package (GitHub packages)
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>gh</id><username>$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="gh::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn deploy -Drevision=${{ env.REVISION }} -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #     run: mvn -Prelease -Drevision=${{ github.event.release.tag_name }} --batch-mode deploy
    #     env:
    #       MAVEN_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
    #       MAVEN_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
    #       MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSWORD }}
